### ISSUE TITLE
BrowserStack bug

### ISSUE THREAD

**Issue by geeknik** [daffainfo/Key-Checker#3]
Hi, I Just grabbed the latest build of your Key Checker and I was testing BrowserStack when I saw this:

```
Choose checkers: 7

You choose BrowserStack Access Key checker
Input your BrowserStack Username:
xxxxx

Input your BrowserStack Key:
xxxxx

Branch.IO Key and Secret invalid
```

Thank you.

**Comment by daffainfo** [comment]
@geeknik Thank you for reporting this issue!, I have fixed the bug

**Comment by geeknik** [comment]
Thanks for the quick fix, however, GitHub is doing the same thing. When I enter GitHub details, it tells me that my Heroku API key is invalid.

**Comment by geeknik** [comment]
The SauceLabs option tells me that my SendGrid API key is invalid as well.
